### PR TITLE
python-modernize -w review setup.py

### PR DESCRIPTION
**Pull request by singuliere**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @singuliere! I've created [OSPR-3200](https://openedx.atlassian.net/browse/OSPR-3200) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@singuliere Thank you for your contribution, please let me know once it is ready to be looked at.

**Comment by singuliere** [comment]
@natabene it's ready for review :tada: :smile:

**Comment by natabene** [comment]
@singuliere Thanks for letting me know @edx/incr-reviewers Can you give this a look?

**Review by estute — APPROVED** [review]
Looks good to me. Thank you for your contribution @singuliere

**Comment by openedx-webhooks** [comment]
@singuliere 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-review&entry.867055334=https://github.com/edx/xblock-review/pull/14&entry.1484655318=https://github.com/singuliere&entry.752974735=2019-03-13+11:53&entry.1917517419=2019-03-19+20:05&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by singuliere** [comment]
@estute thanks for your review :+1:

**Pull request merged**
